[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["npm install", "cd engine && pip install -r requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd engine && python static_server.py"
