"""
Video Generation State Management

Defines the state structure for video generation workflow and provides
utility functions for state manipulation and validation.

Classes:
    VideoGenerationState: TypedDict defining generation workflow state

Functions:
    create_initial_state: Create initial state for a new generation
    validate_state: Validate state structure and required fields
    save_checkpoint: Save a checkpoint in the state
    get_checkpoint: Retrieve a checkpoint from state

Dependencies:
    - typing (TypedDict, Dict, Any, etc.)
    - time (for timestamps)

Usage Example:
    ```python
    from core.orchestrator.state import create_initial_state, save_checkpoint

    # Create initial state
    state = create_initial_state(
        brand_info={"brand_name": "TechCo", ...},
        temp_dir="/tmp/abc",
        generation_id="abc-123",
        progress_callback=callback_fn
    )

    # Save checkpoints as pipeline progresses
    save_checkpoint(state, "planning", {"completed": True, "scenes": 3})
    ```

Author: Relicon Team
Last Updated: 2025-01-09
"""

import time
from typing import Dict, Any, Optional, Callable, TypedDict


class VideoGenerationState(TypedDict):
    """
    Enhanced state for video generation workflow.

    This TypedDict defines the complete state structure used throughout
    the video generation pipeline. Each key represents a critical piece
    of information tracked during generation.

    Fields:
        brand_info: Dictionary containing all brand and product details
                   {brand_name, brand_description, product_name, etc.}
        output_path: Final video file path (set upon completion)
        progress_callback: Optional function to call for progress updates
                          Signature: (progress: int, message: str) -> None
        architecture: Video blueprint generated by planning service
        video_results: Dict mapping scene IDs to video file paths
        audio_path: Path to generated voiceover audio file
        temp_dir: Temporary directory for intermediate files
        success: Whether generation completed successfully
        error: Error message if generation failed
        generation_id: Unique ID for this generation job
        start_time: Unix timestamp when generation started
        checkpoints: Dict of saved checkpoints throughout pipeline

    Example:
        >>> state: VideoGenerationState = {
        ...     "brand_info": {"brand_name": "TechCo"},
        ...     "generation_id": "abc-123",
        ...     ...
        ... }
    """
    brand_info: Dict[str, Any]
    output_path: str
    progress_callback: Optional[Callable[[int, str], None]]
    architecture: Dict[str, Any]
    video_results: Dict[str, Any]
    audio_path: str
    temp_dir: str
    success: bool
    error: Optional[str]
    generation_id: str
    start_time: float
    checkpoints: Dict[str, Any]


def create_initial_state(
    brand_info: Dict[str, Any],
    temp_dir: str,
    generation_id: str,
    progress_callback: Optional[Callable[[int, str], None]] = None
) -> VideoGenerationState:
    """
    Create initial state for a new video generation job.

    Initializes a VideoGenerationState with default values and the
    provided brand information. This state will be mutated throughout
    the generation pipeline.

    Args:
        brand_info: Dictionary containing brand and product details
        temp_dir: Path to temporary directory for intermediate files
        generation_id: Unique identifier for this generation job
        progress_callback: Optional callback for progress updates

    Returns:
        Initialized VideoGenerationState ready for pipeline execution

    Example:
        >>> state = create_initial_state(
        ...     brand_info={
        ...         "brand_name": "TechCo",
        ...         "brand_description": "AI productivity tools",
        ...         "target_audience": "tech professionals",
        ...         "duration": 18,
        ...     },
        ...     temp_dir="/tmp/relicon_abc123",
        ...     generation_id="abc-123"
        ... )
        >>> assert state["success"] == False
        >>> assert state["generation_id"] == "abc-123"

    Note:
        - State is mutable and will be modified by pipeline steps
        - start_time is set to current Unix timestamp
        - All result fields (output_path, video_results, etc.) start empty
    """
    return VideoGenerationState(
        brand_info=brand_info,
        output_path="",
        progress_callback=progress_callback,
        architecture={},
        video_results={},
        audio_path="",
        temp_dir=temp_dir,
        success=False,
        error=None,
        generation_id=generation_id,
        start_time=time.time(),
        checkpoints={}
    )


def validate_state(state: VideoGenerationState) -> bool:
    """
    Validate state structure and required fields.

    Checks that the state contains all required fields and that
    critical fields are properly populated at different pipeline stages.

    Args:
        state: State to validate

    Returns:
        True if state is valid, False otherwise

    Example:
        >>> state = create_initial_state(...)
        >>> assert validate_state(state) == True
        >>>
        >>> # After planning
        >>> state["architecture"] = {"scenes": [...]}
        >>> assert validate_state(state) == True

    Validation Rules:
        - brand_info must be non-empty dict
        - generation_id must be non-empty string
        - temp_dir must be non-empty string
        - If architecture exists, must contain "scenes"
        - If video_results exists, all values must be valid paths
    """
    if not isinstance(state, dict):
        return False

    # Check required fields exist
    required_fields = [
        "brand_info", "generation_id", "temp_dir",
        "start_time", "checkpoints"
    ]

    for field in required_fields:
        if field not in state:
            return False

    # Validate field types and values
    if not state["brand_info"] or not isinstance(state["brand_info"], dict):
        return False

    if not state["generation_id"] or not isinstance(state["generation_id"], str):
        return False

    if not state["temp_dir"] or not isinstance(state["temp_dir"], str):
        return False

    # Validate architecture if present
    if state.get("architecture"):
        if not isinstance(state["architecture"], dict):
            return False

    return True


def save_checkpoint(
    state: VideoGenerationState,
    checkpoint_name: str,
    checkpoint_data: Dict[str, Any]
) -> None:
    """
    Save a checkpoint in the state for tracking pipeline progress.

    Checkpoints allow tracking which pipeline steps have completed
    and storing metadata about each step. Useful for debugging,
    resuming failed generations, and performance analysis.

    Args:
        state: State to save checkpoint in (modified in place)
        checkpoint_name: Name of checkpoint (e.g., "planning", "generation")
        checkpoint_data: Data to save in checkpoint

    Example:
        >>> state = create_initial_state(...)
        >>> save_checkpoint(state, "planning", {
        ...     "completed": True,
        ...     "timestamp": time.time(),
        ...     "architecture_scenes": 3,
        ...     "cost_usd": 0.15
        ... })
        >>> assert "planning" in state["checkpoints"]

    Common Checkpoints:
        - planning: Blueprint generation completed
        - generation: Video and audio generation completed
        - assembly: Final video assembly completed

    Note:
        - Automatically adds timestamp if not provided
        - Previous checkpoint with same name is overwritten
        - State is modified in place
    """
    if "timestamp" not in checkpoint_data:
        checkpoint_data["timestamp"] = time.time()

    state["checkpoints"][checkpoint_name] = checkpoint_data


def get_checkpoint(
    state: VideoGenerationState,
    checkpoint_name: str
) -> Optional[Dict[str, Any]]:
    """
    Retrieve a checkpoint from state.

    Args:
        state: State containing checkpoints
        checkpoint_name: Name of checkpoint to retrieve

    Returns:
        Checkpoint data dict, or None if not found

    Example:
        >>> state = create_initial_state(...)
        >>> save_checkpoint(state, "planning", {"completed": True})
        >>> checkpoint = get_checkpoint(state, "planning")
        >>> assert checkpoint["completed"] == True
        >>>
        >>> missing = get_checkpoint(state, "nonexistent")
        >>> assert missing is None

    Note:
        - Returns None if checkpoint doesn't exist (no exception raised)
        - Returns a reference to the checkpoint (not a copy)
    """
    return state["checkpoints"].get(checkpoint_name)


def get_elapsed_time(state: VideoGenerationState) -> float:
    """
    Get elapsed time since generation started.

    Args:
        state: State containing start_time

    Returns:
        Elapsed time in seconds

    Example:
        >>> state = create_initial_state(...)
        >>> time.sleep(2)
        >>> elapsed = get_elapsed_time(state)
        >>> assert elapsed >= 2.0

    Note:
        - Accurate to microsecond precision
        - Returns time since state creation
    """
    return time.time() - state["start_time"]
